[package]
name = "tinyls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
chrono = "0.4.23"
libc = "0.2.138"
termion = "2.0.1"